apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels: 
    app: image-processing
spec:
  selector:
    app: image-processing
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      
