--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: image-processing
  name: image-processing-deployment
spec: 
  replicas: 4
  selector: 
    matchLabels: 
      app: image-processing
  template: 
    metadata: 
      labels: 
        app: image-processing
    spec: 
      containers: 
        - 
          image: mayursuccessive/image-processing
          name: image-processing
          ports:
            - containerPort: 80
          


