apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
	  app: image-processing
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
	app: image-processing
#    app.kubernetes.io/name: {{ include "mychart.name" . }}
#    app.kubernetes.io/instance: {{ .Release.Name }}
